export enum socketEmitters {
    REQUEST_ID = "requestid",
    CALLUSER = "calluser",
    CALLACCEPTED = "callaccepted",
    ME = "me",
    DISCONNECT = "disconnect",
    ANSWER_CALL = "answercall",
    REJECT_CALL = "rejectcall",
    REVEAL_INIT = "revealinit",
    REVEAL_ACCEPT = "revealaccept",
    ACCEPT_REVEAL = "acceptreveal",
    JOIN_ROOM = "join_room",
    ROOM_FULL = "roomfull",
    USER_CONNECTED = "user-connected",
    USER_DISCONNECTED = "user-disconnected",
    ROOM_LEAVE = "roomleave",
} 